project:
  type: book
  output-dir: docs

book:
  title: "RS_Learning_diary"
  author: "Hilman Prakoso"
  date: "21/03/2023"
  chapters:
    - index.qmd
    - week01.qmd
    - week02.qmd
    - week03.qmd
    - week04.qmd
    - week05.qmd
    - week06.qmd
    - week07.qmd
    - week08.qmd
    - week09.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

